GPS:
  ArduPilot:
    - SIM_GPS1_NOISE
    - SIM_GPS1_VERR_X
    - SIM_GPS1_VERR_Y
    - SIM_GPS1_VERR_Z
    - SIM_GPS1_GLITCH_X
    - SIM_GPS1_GLITCH_Y
    - SIM_GPS1_GLITCH_Z
    - SIM_GPS1_NUMSATS
  PX4:
    - EKF2_GPS_POS_X
    - EKF2_GPS_POS_Y
    - EKF2_GPS_POS_Z
    - EKF2_GPS_P_GATE
    - EKF2_GPS_P_NOISE
    - EKF2_GPS_V_GATE
    - EKF2_GPS_V_NOISE
    - EKF2_GPS_YAW_OFF
GYRO:
  ArduPilot:
    - INS_GYROFFS_X 
    - INS_GYROFFS_Y 
    - INS_GYROFFS_Z 
    - INS_GYR2OFFS_X 
    - INS_GYR2OFFS_Y 
    - INS_GYR2OFFS_Z 
    - INS_GYR3OFFS_X 
    - INS_GYR3OFFS_Y 
    - INS_GYR3OFFS_Z 
    - INS_GYRO_NOISE
    - INS_GYRO_BIAS
    - SIM_GYR1_RND
    - SIM_GYR2_RND
    - SIM_GYR3_RND
  PX4:
    - EKF2_GYR_B_LIM
    - EKF2_GYR_B_NOISE
    - EKF2_GYR_NOISE
    - CAL_GYRO0_XOFF
    - CAL_GYRO0_YOFF
    - CAL_GYRO0_ZOFF
    - CAL_GYRO0_XSCALE
    - CAL_GYRO0_YSCALE
    - CAL_GYRO0_ZSCALE
MAG:
  ArduPilot:
    - SIM_MAG1_BIAS_X  
    - SIM_MAG1_BIAS_Y  
    - SIM_MAG1_BIAS_Z  
    - SIM_MAG1_RND     
    - SIM_MAG1_SCAL_X  
    - SIM_MAG1_SCAL_Y  
    - SIM_MAG1_SCAL_Z  
    - SIM_MAG2_BIAS_X  
    - SIM_MAG2_BIAS_Y  
    - SIM_MAG2_BIAS_Z  
    - SIM_MAG2_RND     
    - SIM_MAG2_SCAL_X  
    - SIM_MAG2_SCAL_Y  
    - SIM_MAG2_SCAL_Z  
    - SIM_MAG3_BIAS_X  
    - SIM_MAG3_BIAS_Y  
    - SIM_MAG3_BIAS_Z  
    - SIM_MAG3_RND     
    - SIM_MAG3_SCAL_X  
    - SIM_MAG3_SCAL_Y  
    - SIM_MAG3_SCAL_Z  
    - SIM_MAG_FAIL_MSK 
  PX4:
    - EKF2_MAG_ACCLIM 
    - EKF2_MAG_B_NOISE
    - EKF2_MAG_CHECK
    - EKF2_MAG_CHK_INC
    - EKF2_MAG_CHK_STR
    - EKF2_MAG_DECL
    - EKF2_MAG_DELAY
    - EKF2_MAG_E_NOISE 
    - EKF2_MAG_GATE
    - EKF2_MAG_NOISE
    - EKF2_MAG_TYPE
    - SIM_MAG_OFFSET_X 
    - SIM_MAG_OFFSET_Y 
    - SIM_MAG_OFFSET_Z
OPTICAL_FLOW:
  ArduPilot:
    - SIM_FLOW_DELAY
    - SIM_FLOW_RND
  PX4:
    - EKF2_OF_CTRL
    - EKF2_OF_DELAY
    - EKF2_OF_GATE
    - EKF2_OF_GYR_SRC
    - EKF2_OF_N_MAX
    - EKF2_OF_N_MIN
    - EKF2_OF_POS_X
    - EKF2_OF_POS_Y
    - EKF2_OF_POS_Z
    - EKF2_OF_QMIN
    - EKF2_OF_QMIN_GND
ACCELEROMETER:
  ArduPilot:
    - SIM_ACC1_BIAS_X 
    - SIM_ACC1_BIAS_Y 
    - SIM_ACC1_BIAS_Z 
    - SIM_ACC1_RND    
    - SIM_ACC1_SCAL_X 
    - SIM_ACC1_SCAL_Y 
    - SIM_ACC1_SCAL_Z 
    - SIM_ACC2_BIAS_X 
    - SIM_ACC2_BIAS_Y 
    - SIM_ACC2_BIAS_Z 
    - SIM_ACC2_RND    
    - SIM_ACC2_SCAL_X 
    - SIM_ACC2_SCAL_Y 
    - SIM_ACC2_SCAL_Z 
    - SIM_ACC3_BIAS_X 
    - SIM_ACC3_BIAS_Y 
    - SIM_ACC3_BIAS_Z 
    - SIM_ACC3_RND    
    - SIM_ACC3_SCAL_X 
    - SIM_ACC3_SCAL_Y 
    - SIM_ACC3_SCAL_Z 
    - SIM_ACCEL1_FAIL 
    - SIM_ACCEL2_FAIL 
    - SIM_ACCEL3_FAIL 
    - SIM_ACC_FAIL_MSK 
  PX4:
    - EKF2_ACC_NOISE
    - EKF2_ACC_B_NOISE
    - EKF2_ABIAS_INIT 